theme: jekyll-theme-dinky
title: "TESK Rental Car service"
image: (images/for homepage.jpg)
description: "Road trippin'!."
gitorg: "https://github.com/Samarthkalanke/roadtrip"
description: 
google_analytics:
